version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 536870912 # ~512 Megabytes
    environment:
      POSTGRES_USER: logoidev_admin
      POSTGRES_PASSWORD: coinsruletheworld
      POSTGRES_DB: logoidev
